// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFktPCR5vgkCvpOd-sFjy1WS-fPgOQ0fM',
    appId: '1:194141151965:web:a41ddbc57f777845d77134',
    messagingSenderId: '194141151965',
    projectId: 'blog-app-94ec9',
    authDomain: 'blog-app-94ec9.firebaseapp.com',
    storageBucket: 'blog-app-94ec9.appspot.com',
    measurementId: 'G-Q0GYFHYYFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClUaRqwlC_pT3DVv7flbt3jVfSAR0KrjI',
    appId: '1:194141151965:android:60aa8cfa0480e216d77134',
    messagingSenderId: '194141151965',
    projectId: 'blog-app-94ec9',
    storageBucket: 'blog-app-94ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADEirrPSVKu2Yocrb3T99XfX8QKa4hCzE',
    appId: '1:194141151965:ios:e3d33a56805d78b6d77134',
    messagingSenderId: '194141151965',
    projectId: 'blog-app-94ec9',
    storageBucket: 'blog-app-94ec9.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADEirrPSVKu2Yocrb3T99XfX8QKa4hCzE',
    appId: '1:194141151965:ios:e3d33a56805d78b6d77134',
    messagingSenderId: '194141151965',
    projectId: 'blog-app-94ec9',
    storageBucket: 'blog-app-94ec9.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFktPCR5vgkCvpOd-sFjy1WS-fPgOQ0fM',
    appId: '1:194141151965:web:729157241ae04642d77134',
    messagingSenderId: '194141151965',
    projectId: 'blog-app-94ec9',
    authDomain: 'blog-app-94ec9.firebaseapp.com',
    storageBucket: 'blog-app-94ec9.appspot.com',
    measurementId: 'G-20L66Z8P28',
  );
}
